[project]
name = "hf-mem"
version = "0.1.0"
description = "A CLI to estimate inference memory requirements for Hugging Face models, written in Python."
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = []
